version: '3.1'
services:
  postgresql_basic_to_advanced:
    image: postgres:13.1-alpine
    restart: always
    container_name: postgresql_basic_to_advanced
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgresql_data:/var/lib/postgresql/data

volumes:
  postgresql_data: